language: go
go:
  - 1.12.x
env:
  - GO111MODULE=on
sudo: false
services:
  - postgresql
before_script:
  - go install github.com/gobuffalo/pop/soda
  - soda create
  - soda migrate
script: go test -v ./...
